name: "Release"

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    if: ${{ github.ref_type == 'tag'}}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Publish Features
        uses: devcontainers/action@v1
        with:
          publish-features: "true"
          base-path-to-features: "./src"
          generate-docs: "true"

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
