name: "CI - Test Features"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        features:
          - shell-history-per-project
          - kubectl-telepresence
        baseImage:
          - debian:latest
          - ubuntu:latest
          - mcr.microsoft.com/devcontainers/base:ubuntu
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install latest devcontainer CLI
        run: npm install -g @devcontainers/cli

      - name: Test feature '${{ matrix.features }}' against '${{ matrix.baseImage }}'
        run: devcontainer features test --features ${{ matrix.features }} --base-image ${{ matrix.baseImage }} .
